# Generated by Django 6.0.6 on 2026-06-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='resourse_url',
            new_name='file_url',
        ),
    ]
