# Generated by Django 6.0.6 on 2026-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_resourse_url_studymaterial_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
