# Generated by Django 6.0.6 on 2026-07-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
    ]
